const memories={
  pipa:{id:'DY-OBJ-001',symbol:'○',type:'OBJECT',year:'',title:'南音乐器',image:'assets/archive/nanyin-instruments.png',imageLabel:'南音乐器实物',desc:'南音演奏由不同乐器共同构成。器物不仅产生声音，也保存着演奏者之间配合、传习与共同排练的记忆。',quote:'器物被再次拿起时，一段声音也重新回到现场。',related:['日常排练','工乂谱','东园书院']},
  score:{id:'DY-OBJ-006',symbol:'○',type:'OBJECT',year:'',title:'工乂谱',image:'assets/archive/gongche-score-01.png',imageLabel:'工乂谱',desc:'工、乂、六、四、一……谱字记录骨干音，也把节拍与演奏传统交给一代代唱奏者。只有在声音与身体动作中，它才真正完整。',quote:'纸上的字不响。人坐在一起，它才成为音乐。',related:['南音乐器','复兴社成员','日常排练']},
  master:{id:'DY-PER-003',symbol:'＋',type:'PERSON',year:'当代',title:'张金田',desc:'作为东园南音记忆中的关键人物，他将个人技艺、社团行动与地方空间重新连接。人物不是资料终点，而是通往更多事件的入口。',quote:'“只要还有人愿意坐下来听，这个声音就不会断。”',related:['南音琵琶','东园南音复兴社','东园书院']},
  rehearsal:{id:'DY-EVT-008',symbol:'◇',type:'EVENT',year:'',title:'东园南音复兴社日常排练',image:'assets/archive/nanyin-rehearsal.png',imageLabel:'日常排练记录',desc:'成员围坐演奏，乐器、身体动作与彼此配合共同构成排练现场。正是这些日常时刻，让南音成为仍在发生的社区生活。',quote:'一次排练，也是一段共同记忆被继续书写的过程。',related:['东园书院','南音乐器','工乂谱']},
  hallMemory:{id:'DY-EVT-004',symbol:'◇',type:'EVENT',year:'',title:'南音汇唱活动',image:'assets/archive/nanyin-gathering-2019.png',imageLabel:'南音汇唱现场',desc:'南音社团以汇唱和交流的方式走出日常排练空间。舞台上的演奏连接不同社团，也让地方声音进入更广阔的公共文化现场。',quote:'从日常排练到公共演出，声音连接起更多共同参与的人。',related:['东方红大礼堂','南音乐器','东园南音复兴社']},
  canalStory:{id:'DY-PLACE-004',symbol:'□',type:'PLACE',year:'多代共存',title:'东园水渠',desc:'水渠连接日常路径、童年经验与村落空间。它不直接演奏南音，却是许多居民讲述“从哪里走过”的起点。',quote:'水声和远处的琵琶，有时会在记忆里叠在一起。',related:['童年路径','环境声音','东园书院']},
  ritual:{id:'DY-EVT-011',symbol:'◇',type:'EVENT',year:'仪式时间',title:'郎君祭',desc:'南音社团以仪式追认共同传统。声音、供奉、行礼与人际关系在同一时刻相遇，使文化记忆从知识成为行动。',quote:'礼不是表演，它确认我们从哪里来。',related:['池王爷宫','工乂谱','社团成员']}
  ,communityToday:{id:'DY-PLACE-012',symbol:'□',type:'PLACE',year:'今日',title:'老空间里的今日生活',image:'assets/archive/community-today.jpg',imageLabel:'东园社区今日景象',desc:'历史建筑并没有离开日常生活。人们仍在这里相聚、交谈，让旧空间继续承载当代社区关系。',quote:'一处空间被持续使用时，记忆就不只停留在过去。',related:['东园书院','社区日常','地方全貌']}
};
const scenes={
 academy:{title:'东园书院',id:'DY-PLACE-001',image:'assets/archive/dongyuan-academy.png',sub:'书院空间连接着地方生活、南音排练与社区记忆。',spots:[['pipa',57,32],['score',73,49],['master',45,58],['rehearsal',65,67],['communityToday',29,43]]},
 hall:{title:'东方红大礼堂',id:'DY-PLACE-002',image:'assets/archive/dongfanghong-hall.png',sub:'公共文化空间承载演出、相聚与共同观看的记忆。',spots:[['hallMemory',61,39],['master',43,57],['pipa',73,62]]},
 temple:{title:'池王爷宫',id:'DY-PLACE-003',sub:'祭祀让声音成为共同体确认来处的方式。',spots:[['ritual',61,41],['score',46,59],['master',75,63]]},
 canal:{title:'东园水渠',id:'DY-PLACE-004',sub:'水流经过村落，也经过不同人的童年。',spots:[['canalStory',56,46],['rehearsal',74,58],['pipa',42,64]]}
};
const translations={
  '东园':'DONGYUAN','东园南音数字记忆档案':'DONGYUAN NANYIN DIGITAL MEMORY ARCHIVE','听见':'HEAR','进入记忆':'ENTER THE MEMORY','WATER REMEMBERS / 水有记忆':'WATER REMEMBERS',
  '一处地方从来不只属于此刻。':'A place never belongs only to the present.','声音仍在旧墙与水渠之间回响。':'Sound still echoes between old walls and waterways.',
  '东园记忆地图':'DONGYUAN MEMORY MAP','从空间进入记忆。选择一处地点，听见它未曾消失的声响。':'Enter memory through space. Choose a place and listen to the sounds that never disappeared.',
  '东园书院':'DONGYUAN ACADEMY','东方红大礼堂':'DONGFANGHONG ASSEMBLY HALL','池王爷宫':'CHI WANGYE TEMPLE','东园水渠':'DONGYUAN CANAL','防空洞':'AIR-RAID SHELTER',
  '文化空间':'CULTURAL SPACE','仪式空间':'RITUAL SPACE','公共空间':'PUBLIC SPACE','场所不是背景':'PLACE IS NOT A BACKDROP',
  '它保存动作、声音与相遇。点击一处坐标，让一条隐匿的记忆重新显影。':'It holds gestures, sounds and encounters. Select a coordinate to bring a hidden memory back into view.',
  '← 返回地图':'← BACK TO MAP','旧墙之内，日常排练让古老声腔继续发生。':'Within the old walls, everyday rehearsals keep an ancient sound alive.',
  '散场以后，凳脚声与旧曲仍留在一代人的回忆里。':'After the gathering, moving stools and old melodies remain in a generation’s memory.',
  '祭祀让声音成为共同体确认来处的方式。':'Ritual turns sound into a way for the community to remember where it came from.',
  '水流经过村落，也经过不同人的童年。':'Water flows through the village and through many different childhoods.',
  '听见这段记忆':'LISTEN TO THIS MEMORY','＋ 串入我的记忆线':'＋ ADD TO MY MEMORY THREAD','展开 ↗':'EXPAND ↗','从一个记忆开始':'BEGIN WITH ONE MEMORY',
  '把一段记忆':'TURN A MEMORY','变成':'INTO','南音':'NANYIN','写下一句话。系统会从记忆的地点、情绪与时间中，选择一段南音式旋律回应你。':'Write one sentence. The system responds with a Nanyin-inspired melody shaped by place, emotion and time.',
  '你的记忆 / YOUR MEMORY':'YOUR MEMORY','小时候，我常跟奶奶经过东园的水渠……':'When I was young, I often walked past Dongyuan Canal with my grandmother…','使用一段示例':'USE AN EXAMPLE',
  '生成一段记忆':'GENERATE A MEMORY','水渠旁的旧日回声':'OLD ECHOES BY THE CANAL','水 · 怀旧 · 缓板':'WATER · NOSTALGIA · ADAGIO',
  '一面仍在生长的':'A LIVING','记忆墙':'MEMORY WALL','个人讲述被听见，也可能成为下一条集体档案。':'A personal story can be heard and become the next collective record.',
  '东园当代影像档案':'CONTEMPORARY DONGYUAN IMAGE ARCHIVE','地方全貌':'PLACE IN FULL','村落、旧厝与新的城市边界':'THE VILLAGE, HISTORIC HOMES AND A CHANGING URBAN EDGE','当代影像':'CONTEMPORARY IMAGE','公共建筑':'PUBLIC ARCHITECTURE','建筑记忆':'ARCHITECTURAL MEMORY','张世清宅':'ZHANG SHIQING HOUSE','不可移动文物':'IMMOVABLE CULTURAL HERITAGE','社区日常':'COMMUNITY LIFE','老空间里的今日生活':'DAILY LIFE IN A HISTORIC SPACE','东园社区今日景象':'DONGYUAN COMMUNITY TODAY',
  '东园社区全景航拍':'AERIAL VIEW OF DONGYUAN COMMUNITY','东方红大礼堂立面细节':'FACADE DETAIL OF DONGFANGHONG ASSEMBLY HALL','张世清宅红砖建筑细节':'RED-BRICK DETAIL OF ZHANG SHIQING HOUSE','今日东园社区室内生活景象':'EVERYDAY LIFE INSIDE DONGYUAN COMMUNITY TODAY',
  '历史建筑并没有离开日常生活。人们仍在这里相聚、交谈，让旧空间继续承载当代社区关系。':'Historic buildings remain part of everyday life. People still gather and talk here, allowing old spaces to hold present-day community relationships.','一处空间被持续使用时，记忆就不只停留在过去。':'When a place remains in use, memory does not stay only in the past.',
  '东园旧影 · 1987':'DONGYUAN · 1987','礼堂散场以后':'AFTER THE HALL EMPTIED','小时候只记得大人们搬着长凳。很多年以后再听到拍板，才知道那晚唱的是南音。':'As a child, I only remembered adults moving long benches. Years later, hearing the clappers again, I learned that the music that night was Nanyin.',
  '林阿姨 · 东园居民':'AUNT LIN · RESIDENT','声一起，村子就不只是一个地方。它会变成许多人共同记得的样子。':'When the music begins, the village is no longer only a place. It becomes what many people remember together.',
  '复兴社成员':'REVIVAL SOCIETY MEMBER','东园水渠 · 今日':'DONGYUAN CANAL · TODAY','水渠边的路':'THE PATH BY THE CANAL','奶奶总在这里放慢脚步。':'Grandmother always slowed down here.','鹭岛小陈':'XIAO CHEN · XIAMEN',
  '旧窗与晚风':'OLD WINDOWS AND EVENING WIND','“我记得书院窗外的风。”':'“I remember the wind outside the academy window.”','山海之间':'BETWEEN MOUNTAIN AND SEA',
  '一张没有写年份的合影':'AN UNDATED GROUP PHOTO','父亲站在最后一排，怀里抱着琵琶。照片背面只写了两个字：东园。':'Father stood in the last row holding a pipa. On the back of the photograph were only two words: Dongyuan.','张先生':'MR. ZHANG',
  '我的东园南音':'MY DONGYUAN NANYIN','你走过的路径，已经成为这座记忆档案的一部分。':'The path you took has become part of this memory archive.','尚未串联记忆':'NO MEMORIES CONNECTED YET','回到地图，点击场景中的记忆热点。':'Return to the map and select a memory hotspot.','开始探索':'START EXPLORING',
  '南音琵琶':'NANYIN PIPA','清末至今':'LATE QING TO PRESENT','横抱的琵琶以指甲弹拨，音色清越，是南音上四管的骨架。它既是一件乐器，也保存着师徒间无法只靠文字说明的手势。':'Held horizontally and plucked with the fingernails, the pipa gives Nanyin its clear upper-register frame. It is both an instrument and a vessel for gestures that words alone cannot transmit.',
  '“手一放上去，就知道老师当年为什么要我慢下来。”':'“The moment my hand rests on it, I understand why my teacher asked me to slow down.”',
  '工乂谱':'GONGCHE NOTATION','二十世纪':'20TH CENTURY','工、乂、六、四、一……谱字记录骨干音，也把节拍与演奏传统交给一代代唱奏者。只有在声音与身体动作中，它才真正完整。':'Gong, yi, liu, si, yi… The characters record principal tones and carry rhythm and performance practice across generations. They become complete only through sound and bodily action.','纸上的字不响。人坐在一起，它才成为音乐。':'Characters on paper are silent. They become music when people sit together.',
  '张金田':'ZHANG JINTIAN','当代':'CONTEMPORARY','作为东园南音记忆中的关键人物，他将个人技艺、社团行动与地方空间重新连接。人物不是资料终点，而是通往更多事件的入口。':'A key figure in Dongyuan’s Nanyin memory, he reconnects personal skill, collective action and local space. A person is not the end of an archive, but an entry into more events.','“只要还有人愿意坐下来听，这个声音就不会断。”':'“As long as someone is willing to sit and listen, this sound will not be broken.”',
  '一次日常排练':'AN EVERYDAY REHEARSAL','今日':'TODAY','没有舞台，也没有正式观众。成员围坐、校音、停下、重来。正是这些普通而重复的时刻，让南音成为仍在发生的社区生活。':'There is no stage and no formal audience. Members sit together, tune, stop and begin again. These ordinary repetitions keep Nanyin alive as community life.','门外有人路过，门内的人继续唱。':'Someone passes outside; inside, the singing continues.',
  '礼堂里的南音夜':'A NANYIN NIGHT IN THE HALL','1980年代':'1980S','公共礼堂容纳演出，也容纳散场后的闲谈与搬凳声。集体记忆往往不是一场演出的曲目单，而是共同在场的细节。':'The public hall held performances, but also conversation and the scraping of benches afterward. Collective memory often lives not in a set list, but in the details of being there together.','“我不记得唱了什么，只记得那晚人很多。”':'“I do not remember what was sung. I only remember how many people were there.”',
  '多代共存':'ACROSS GENERATIONS','水渠连接日常路径、童年经验与村落空间。它不直接演奏南音，却是许多居民讲述“从哪里走过”的起点。':'The canal links daily routes, childhood experience and village space. It does not play Nanyin, yet it begins many residents’ stories of where they once walked.','水声和远处的琵琶，有时会在记忆里叠在一起。':'In memory, flowing water sometimes overlaps with a distant pipa.',
  '郎君祭':'LANGJUN RITUAL','仪式时间':'RITUAL TIME','南音社团以仪式追认共同传统。声音、供奉、行礼与人际关系在同一时刻相遇，使文化记忆从知识成为行动。':'Through ritual, Nanyin societies reaffirm a shared tradition. Sound, offerings, gestures and relationships meet, turning cultural memory from knowledge into action.','礼不是表演，它确认我们从哪里来。':'Ritual is not performance; it confirms where we come from.',
  '东园南音复兴社':'DONGYUAN NANYIN REVIVAL SOCIETY','日常排练':'EVERYDAY REHEARSAL','社团成员':'SOCIETY MEMBERS','老照片':'OLD PHOTOGRAPH','社区居民':'COMMUNITY RESIDENTS','童年路径':'CHILDHOOD PATH','环境声音':'AMBIENT SOUND','洞箫':'DONGXIAO FLUTE',
  '我的南音创作':'MY NANYIN CREATION','正在聆听记忆…':'LISTENING TO YOUR MEMORY…','再生成一个版本':'GENERATE ANOTHER VERSION','跟随奶奶的慢板':'A SLOW MELODY WITH GRANDMOTHER','东园的一段回声':'AN ECHO OF DONGYUAN',
  '南音乐器':'NANYIN INSTRUMENTS','南音乐器实物':'NANYIN INSTRUMENTS','器物不仅产生声音，也保存着演奏者之间配合、传习与共同排练的记忆。':'Instruments do more than produce sound; they preserve memories of ensemble, transmission and rehearsal.','南音演奏由不同乐器共同构成。器物不仅产生声音，也保存着演奏者之间配合、传习与共同排练的记忆。':'Nanyin performance is formed by an ensemble of instruments. These objects preserve memories of coordination, transmission and rehearsal.','器物被再次拿起时，一段声音也重新回到现场。':'When an instrument is lifted again, a sound returns to the place.',
  '东园南音复兴社日常排练':'DONGYUAN NANYIN REVIVAL SOCIETY REHEARSAL','日常排练记录':'EVERYDAY REHEARSAL','成员围坐演奏，乐器、身体动作与彼此配合共同构成排练现场。正是这些日常时刻，让南音成为仍在发生的社区生活。':'Members sit together to play; instruments, bodily gestures and coordination form the rehearsal scene. These everyday moments keep Nanyin alive as community life.','一次排练，也是一段共同记忆被继续书写的过程。':'Each rehearsal continues the writing of a shared memory.',
  '南音汇唱活动':'NANYIN GATHERING','南音汇唱现场':'NANYIN GATHERING','南音社团以汇唱和交流的方式走出日常排练空间。舞台上的演奏连接不同社团，也让地方声音进入更广阔的公共文化现场。':'Through gatherings and exchange, Nanyin societies move beyond everyday rehearsal spaces. Performance connects different groups and carries local sound into a wider public cultural setting.','从日常排练到公共演出，声音连接起更多共同参与的人。':'From rehearsal to public performance, sound connects a wider community of participants.',
  '书院空间连接着地方生活、南音排练与社区记忆。':'The academy connects local life, Nanyin rehearsal and community memory.','公共文化空间承载演出、相聚与共同观看的记忆。':'This public cultural space holds memories of performance, gathering and shared spectatorship.',
  '已串入你的记忆线':'ADDED TO YOUR MEMORY THREAD','这段记忆已在线上':'THIS MEMORY IS ALREADY IN YOUR THREAD','先写下一小段记忆':'WRITE A SHORT MEMORY FIRST','一段新的南音记忆已生成':'A NEW NANYIN MEMORY HAS BEEN GENERATED','作品已保存到个人记忆':'CREATION SAVED TO MY MEMORY','作品已加入社区记忆墙（原型）':'CREATION ADDED TO THE COMMUNITY WALL (PROTOTYPE)','个人记忆卡已下载':'PERSONAL MEMORY CARD DOWNLOADED','分享链接已复制':'SHARE LINK COPIED'
};
let currentLang=localStorage.getItem('dongyuan-language')||'zh';
let thread=JSON.parse(localStorage.getItem('dongyuan-thread')||'[]');let currentMemory=null;let audioCtx=null;let playing=false,playTimer=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const tr=text=>currentLang==='en'?(translations[text]||text):text;
function resetI18n(root){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);while(walker.nextNode())delete walker.currentNode._i18nZh}
function applyLanguage(){
  document.documentElement.lang=currentLang==='en'?'en':'zh-CN';
  document.title=currentLang==='en'?'Hear Dongyuan | Digital Nanyin Memory':'听见东园｜东园南音数字记忆';
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode:n=>['SCRIPT','STYLE'].includes(n.parentElement?.tagName)?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});
  while(walker.nextNode()){const n=walker.currentNode,raw=n.textContent,trim=raw.trim();if(!trim)continue;if(n._i18nZh===undefined)n._i18nZh=trim;const value=currentLang==='en'?(translations[n._i18nZh]||n._i18nZh):n._i18nZh;n.textContent=raw.replace(trim,value)}
  $$('[alt]').forEach(el=>{if(!el.dataset.zhAlt)el.dataset.zhAlt=el.getAttribute('alt');el.setAttribute('alt',currentLang==='en'?(translations[el.dataset.zhAlt]||el.dataset.zhAlt):el.dataset.zhAlt)});
  $$('.visual-archive[aria-label]').forEach(el=>{if(!el.dataset.zhAria)el.dataset.zhAria=el.getAttribute('aria-label');el.setAttribute('aria-label',currentLang==='en'?(translations[el.dataset.zhAria]||el.dataset.zhAria):el.dataset.zhAria)});
  $('#memoryInput').placeholder=currentLang==='en'?translations['小时候，我常跟奶奶经过东园的水渠……']:'小时候，我常跟奶奶经过东园的水渠……';
  const spans=$$('#languageToggle span');spans[0].classList.toggle('active',currentLang==='zh');spans[1].classList.toggle('active',currentLang==='en');
  $('#languageToggle').setAttribute('aria-label',currentLang==='zh'?'Switch to English':'切换到中文');
  $('#menuButton').textContent=currentLang==='en'?'MENU':'目录';
  $('#personalDate').textContent=new Intl.DateTimeFormat(currentLang==='en'?'en-GB':'zh-CN').format(new Date());
}
$('#languageToggle').onclick=()=>{currentLang=currentLang==='zh'?'en':'zh';localStorage.setItem('dongyuan-language',currentLang);renderGraph()};
function go(id){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===id));const dark=['home','scene'].includes(id);$('#siteHeader').classList.toggle('dark-ui',dark);$('#siteHeader nav').classList.remove('open');window.scrollTo(0,0);if(id==='memory')renderGraph();applyLanguage();}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
$('#menuButton').onclick=()=>$('#siteHeader nav').classList.toggle('open');
function openScene(key){const s=scenes[key];if(!s)return;$('#sceneTitle').textContent=s.title;$('#sceneId').textContent=s.id;$('#sceneSubtitle').textContent=s.sub;$('#sceneImage').style.backgroundImage=`linear-gradient(90deg,rgba(10,12,10,.42),rgba(10,12,10,.08)),url('${s.image||'assets/dongyuan-memory.jpg'}')`;resetI18n($('#sceneTitle'));resetI18n($('#sceneSubtitle'));const hs=$('#hotspots');hs.innerHTML='';s.spots.forEach(([id,x,y])=>{const m=memories[id],b=document.createElement('button');b.className='hotspot';b.style.left=x+'%';b.style.top=y+'%';b.dataset.label=tr(m.title);b.textContent=m.symbol;b.onclick=()=>openCard(id);hs.appendChild(b)});go('scene');}
$$('.place-node:not(.locked)').forEach(n=>{n.onclick=()=>openScene(n.dataset.scene);n.onkeydown=e=>{if(e.key==='Enter')openScene(n.dataset.scene)}});
function openCard(id){currentMemory=id;const m=memories[id];$('#cardIndex').textContent=m.id;$('#cardSymbol').textContent=m.symbol;$('#cardType').textContent=m.type;$('#cardYear').textContent=m.year;$('#cardTitle').textContent=m.title;$('#cardDescription').textContent=m.desc;$('#cardQuote').textContent=m.quote;const image=$('#cardImage');image.style.backgroundImage=m.image?`linear-gradient(0deg,rgba(15,18,15,.55),transparent 60%),url('${m.image}')`:'';image.classList.toggle('has-image',Boolean(m.image));image.innerHTML=`<span>${m.imageLabel||'记忆影像'}</span>`;$('#relatedLinks').innerHTML=m.related.map(x=>`<button><span>${x}</span><span aria-hidden="true"> →</span></button>`).join('');[$('#cardYear'),$('#cardTitle'),$('#cardDescription'),$('#cardQuote'),image,$('#relatedLinks')].forEach(resetI18n);applyLanguage();$('#memoryCard').classList.add('open')}
$('#cardClose').onclick=()=>$('#memoryCard').classList.remove('open');
$('#threadAdd').onclick=()=>{if(currentMemory&&!thread.includes(currentMemory)){thread.push(currentMemory);localStorage.setItem('dongyuan-thread',JSON.stringify(thread));updateThread();toast('已串入你的记忆线')}else toast('这段记忆已在线上')};
function updateThread(){const box=$('#threadMini');$('#memoryCount').textContent=String(thread.length).padStart(2,'0');box.innerHTML=thread.length?thread.slice(-5).map(id=>`<i></i><small class="thread-node-mini">${id==='creation'?'我的南音创作':memories[id].title}</small>`).join(''):'<i></i><small>从一个记忆开始</small>';resetI18n(box);applyLanguage()}
$$('#timeOptions button').forEach((b,i)=>b.onclick=()=>{$$('#timeOptions button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#scene').dataset.time=b.dataset.time;$('#scenePeriod').textContent=b.dataset.time;$('.track i').style.left=(i/3*100)+'%'});
function beepSequence(){if(playing)return;audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();playing=true;$('#soundToggle b').textContent='SOUND ON';$('#soundToggle').setAttribute('aria-pressed','true');const scale=[261.6,293.7,349.2,392,440,392,349.2,293.7];scale.forEach((f,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,audioCtx.currentTime+i*.28);g.gain.linearRampToValueAtTime(.045,audioCtx.currentTime+i*.28+.03);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+i*.28+.25);o.connect(g).connect(audioCtx.destination);o.start(audioCtx.currentTime+i*.28);o.stop(audioCtx.currentTime+i*.28+.27)});setTimeout(()=>playing=false,2400)}
$('#soundToggle').onclick=beepSequence;$('#cardAudio').onclick=()=>{beepSequence();if(currentMemory&&!thread.includes(currentMemory)){$('#threadAdd').click()}};
const input=$('#memoryInput');input.oninput=()=>$('#charCount').textContent=`${input.value.length} / 80`;$('#examplePrompt').onclick=()=>{input.value=currentLang==='en'?'When I was young, I often walked past Dongyuan Canal with my grandmother.':'小时候，我常跟奶奶经过东园的水渠。';input.oninput()};
function drawWave(){const c=$('#waveform'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.strokeStyle='#9b4438';x.lineWidth=2;x.beginPath();for(let i=0;i<c.width;i+=4){const y=60+Math.sin(i*.055)*18*Math.sin(i*.009)+Math.sin(i*.17)*7;x.lineTo(i,y)}x.stroke()}
$('#generateButton').onclick=()=>{if(!input.value.trim()){input.focus();toast('先写下一小段记忆');return}$('#generateButton span').textContent=tr('正在聆听记忆…');setTimeout(()=>{$('#generation').classList.add('visible');$('#genId').textContent=String(Math.floor(Math.random()*900)+100);const lower=input.value.toLowerCase();const title=(input.value.includes('水')||lower.includes('water')||lower.includes('canal'))?'水渠旁的旧日回声':(input.value.includes('奶奶')||lower.includes('grandmother'))?'跟随奶奶的慢板':'东园的一段回声';$('#generatedTitle').textContent=tr(title);drawWave();$('#generateButton span').textContent=tr('再生成一个版本');toast('一段新的南音记忆已生成')},900)};
$('#playGenerated').onclick=()=>{beepSequence();let i=0,sec=0;clearInterval(playTimer);playTimer=setInterval(()=>{$$('#score i').forEach(x=>x.classList.remove('active'));$$('#score i')[i%8].classList.add('active');sec++;$('#playTime').textContent=`00:${String(sec).padStart(2,'0')} / 00:18`;i++;if(sec>=18){clearInterval(playTimer);$('#playTime').textContent='00:00 / 00:18'}},280)};
$('#saveGenerated').onclick=()=>{if(!thread.includes('creation'))thread.push('creation');localStorage.setItem('dongyuan-thread',JSON.stringify(thread));updateThread();toast('作品已保存到个人记忆')};$('#shareGenerated').onclick=()=>toast('作品已加入社区记忆墙（原型）');
$$('#filters button').forEach(b=>b.onclick=()=>{$$('#filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.wall-card').forEach(c=>c.style.display=b.textContent==='ALL'||c.dataset.type===b.textContent?'block':'none')});
$$('.wall-card footer button').forEach(b=>b.onclick=()=>{const n=parseInt(b.textContent.match(/\d+/)?.[0]||0)+1;b.textContent='♥ '+n;b.style.color='#9b4438'});
function renderGraph(){const g=$('#memoryGraph');const nodes=thread.filter(id=>id==='creation'||memories[id]);g.querySelectorAll('.graph-node').forEach(n=>n.remove());$('.empty-graph').style.display=nodes.length?'none':'grid';const svg=$('#graphLines');svg.innerHTML='';const coords=[[8,16],[31,55],[55,13],[76,57],[88,20],[47,68],[16,68]];nodes.slice(0,7).forEach((id,i)=>{const m=id==='creation'?{type:'MY MEMORY',title:'我的南音创作'}:memories[id],d=document.createElement('div');d.className='graph-node';d.style.left=coords[i][0]+'%';d.style.top=coords[i][1]+'%';d.innerHTML=`<small>${m.type}</small><b>${m.title}</b>`;g.appendChild(d);if(i){const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',coords[i-1][0]+5+'%');line.setAttribute('y1',coords[i-1][1]+12+'%');line.setAttribute('x2',coords[i][0]+5+'%');line.setAttribute('y2',coords[i][1]+12+'%');svg.appendChild(line)}});$('#statMemories').textContent=String(nodes.filter(x=>x!=='creation').length).padStart(2,'0');$('#statPlaces').textContent=String(new Set(nodes.filter(x=>x!=='creation').map(x=>memories[x].type==='PLACE'?x:'academy')).size).padStart(2,'0');$('#statSounds').textContent=String(nodes.length?Math.min(3,nodes.length):0).padStart(2,'0');$('#statCreations').textContent=String(nodes.includes('creation')?1:0).padStart(2,'0');applyLanguage()}
$('#downloadMemory').onclick=()=>{const text=['MY DONGYUAN NANYIN / 我的东园南音','',...thread.map(id=>id==='creation'?'MY MEMORY - 我的南音创作':`${memories[id].type} - ${memories[id].title}`)].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download='我的东园南音.txt';a.click();URL.revokeObjectURL(a.href);toast('个人记忆卡已下载')};$('#shareMemory').onclick=()=>{navigator.clipboard?.writeText(location.href);toast('分享链接已复制')};
function toast(msg){const t=$('#toast');t.textContent=tr(msg);t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
$('#personalDate').textContent=new Intl.DateTimeFormat('zh-CN').format(new Date());applyLanguage();updateThread();
